### ISSUE TITLE
Drop Button [Sugerencia de comportamiento]

### ISSUE THREAD

**Issue by javatlacati** [JorgeAntrax/website#10]
En la sección de

>Componentes > Dropdown

los botones dropdown no hacen nada cuando uno les da click por segunda vez.
Tal vez sería bueno agregarle el comportamiento de que cierre el dropdown al darle el segundo click.

**Comment by JorgeAntrax** [comment]
esa parte es un proceso de javascript, como lo dice hay en la web en texto informativo, utiliza el efecto focus, podria ponerlo asi como comentas y como esta en la parte de las ventanas modal, poner un ejemplo con el código JS.
