### ISSUE TITLE
Blockquote sin símbolos

### ISSUE THREAD

**Issue by javatlacati** [JorgeAntrax/website#13]
El símbolo de `"` aparece siempre en los bloques de comentarios, y los hace dependientes de una tipografía en particular, si esta no estuviera se cargaría como un caracter molesto.

Se sugiere quitar el icono o permitir personalizarlo.

**Comment by JorgeAntrax** [comment]
ok

**Comment by javatlacati** [comment]
```
blockquote::before {
    content: '\201C';
```
