### ISSUE TITLE
Modals darkened on mobile

### ISSUE THREAD

**Issue by javatlacati** [JorgeAntrax/website#15]
I'm testing from an iOS device please take a look at the image  ![Image](https://i.imgur.com/s2qJTcL.jpg)

**Comment by JorgeAntrax** [comment]
Será cuestión del dispositivo no? Te mando una captura por inbox

**Comment by JorgeAntrax** [comment]
![screenshot_20171209-105240](https://user-images.githubusercontent.com/30363785/33798050-4a2a73aa-dccf-11e7-80ee-ab67b3c0b54e.png)
