### ISSUE TITLE
Galería [Sugerencia]

### ISSUE THREAD

**Issue by javatlacati** [JorgeAntrax/website#5]
Tal vez sería bueno armar una página de galería en la que se mostraran proyectos o sitios que actualemnte usen Kimera

**Comment by JorgeAntrax** [comment]
Es una opcion ya contemplada, pero aún no hay sitios construidos.

**Comment by javatlacati** [comment]
Se puede poner una página con los cuadros vacíos y un comentario para que los que quieran que sus proyectos aparezcan los puedan mandar

**Comment by JorgeAntrax** [comment]
Tienes razón
