### ISSUE TITLE
Sección de Variables agresiva

### ISSUE THREAD

**Issue by javatlacati** [JorgeAntrax/website#6]
Favor de no usar texto en rojo con fondo blanco aún para aquellos que no tenemos dificultades visuales para ver este color nos resulta molesto.

Específicamente hallé esto en

    Introducción > Colores

**Comment by javatlacati** [comment]
Se sigue viendo el texto en rojo

**Comment by JorgeAntrax** [comment]
que color me recomiendas poner hay? o en donde dices especificamente? quite casi todo el texto reojo y lo puse negro!
