### ISSUE TITLE
Expand double click

### ISSUE THREAD

**Issue by javatlacati** [JorgeAntrax/website#7]
En las secciones de código sale la leyenda

> </ Expand double click >

Aparentemente no tiene razón de ser.

Esto lo probé en los navegadores firefox y chrome.

En su lugar sugiero remplazar esos códigos por live snippets de jsfiddle o de codepen, si requirieran de varios archivos, de plnkr.

**Comment by JorgeAntrax** [comment]
Ohh es solo una leyenda que al darle doble click al snippet se expande el código de forma vertical mostrando todo el snippet

**Comment by JorgeAntrax** [comment]
Pero me gusta la idea de incrustar jsfiddle o codepen
